
spring:
  application:
    name: proyecto-arquitectura-corte1

datasource:
  my-connection:
    jdbc-url: jdbc:postgresql://localhost:5432/bd_arquitectura_corte1
    username: walrus
    password: 123456789
    maximum-pool-size: 10
    pool-name: "crud-pool"
    auto-commit: true


